// =====================================================
// kosakata-data.js
// Data kosakata N5 untuk aplikasi DeX Gaku, dikelompokkan
// ke dalam 12 kategori.
//
// Setiap entri: { kata, romaji, arti }
// "kata" = tulisan Jepang (kanji/hiragana/katakana campur,
// ditambah cara baca hiragana di dalam kurung khusus untuk KANJI)
// =====================================================

var KOSAKATA_CATEGORIES = [
  {
    key: "orang-keluarga",
    no: 1,
    nama: "Orang & Keluarga",
    icon: "&#128101;",
    contoh: "人・私・父・母",
    kata: [
      { kata: "人 (ひと)", romaji: "hito", arti: "orang" },
      { kata: "私 (わたし)", romaji: "watashi", arti: "saya" },
      { kata: "あなた", romaji: "anata", arti: "anda" },
      { kata: "誰 (だれ)", romaji: "dare", arti: "siapa" },
      { kata: "誰か (だれか)", romaji: "dareka", arti: "seseorang" },
      { kata: "誰も (だれも)", romaji: "daremo", arti: "siapapun" },
      { kata: "みんな", romaji: "minna", arti: "semua orang" },
      { kata: "大勢 (おおぜい)", romaji: "oozei", arti: "orang banyak" },
      { kata: "一人 (ひとり)", romaji: "hitori", arti: "sendiri / satu orang" },
      { kata: "二人 (ふたり)", romaji: "futari", arti: "berdua / dua orang" },
      { kata: "男 (おとこ)", romaji: "otoko", arti: "laki-laki" },
      { kata: "女 (おんな)", romaji: "onna", arti: "perempuan" },
      { kata: "男の子 (おとこのこ)", romaji: "otoko no ko", arti: "anak laki-laki" },
      { kata: "女の子 (おんなのこ)", romaji: "onna no ko", arti: "anak perempuan" },
      { kata: "子ども (こども)", romaji: "kodomo", arti: "anak-anak" },
      { kata: "大人 (おとな)", romaji: "otona", arti: "dewasa" },
      { kata: "姉 (あね) / お姉さん (おねえさん)", romaji: "ane / onee-san", arti: "kakak perempuan" },
      { kata: "兄 (あに) / お兄さん (おにいさん)", romaji: "ani / onii-san", arti: "kakak laki-laki" },
      { kata: "妹 (いもうと)", romaji: "imouto", arti: "adik perempuan" },
      { kata: "弟 (おとうと)", romaji: "otouto", arti: "adik laki-laki" },
      { kata: "母 (はは) / お母さん (おかあさん)", romaji: "haha / okaa-san", arti: "ibu" },
      { kata: "父 (ちち) / お父さん (おとうさん)", romaji: "chichi / otou-san", arti: "ayah" },
      { kata: "お祖母さん (おばあさん)", romaji: "obaasan", arti: "nenek" },
      { kata: "お祖父さん (おじいさん)", romaji: "ojiisan", arti: "kakek" },
      { kata: "伯母さん (おばさん)", romaji: "obasan", arti: "bibi/tante" },
      { kata: "伯父さん (おじさん)", romaji: "ojisan", arti: "paman" },
      { kata: "夫 (おっと) / ご主人 (ごしゅじん)", romaji: "otto / goshujin", arti: "suami" },
      { kata: "妻 (つま) / 奥さん (おくさん)", romaji: "tsuma / oku-san", arti: "istri" },
      { kata: "兄弟 (きょうだい)", romaji: "kyoudai", arti: "saudara" },
      { kata: "家族 (かぞく)", romaji: "kazoku", arti: "keluarga" },
      { kata: "両親 (りょうしん)", romaji: "ryoushin", arti: "orang tua" },
      { kata: "外国人 (がいこくじん)", romaji: "gaikokujin", arti: "orang asing" },
      { kata: "留学生 (りゅうがくせい)", romaji: "ryuugakusei", arti: "pelajar asing" },
      { kata: "友達 (ともだち)", romaji: "tomodachi", arti: "teman" }
    ]
  },
  {
    key: "rumah-kehidupan",
    no: 2,
    nama: "Rumah & Kehidupan",
    icon: "&#127968;",
    contoh: "家・部屋・机・窓",
    kata: [
      { kata: "家 (いえ) / うち", romaji: "ie / uchi", arti: "rumah" },
      { kata: "部屋 (へや)", romaji: "heya", arti: "kamar" },
      { kata: "机 (つくえ)", romaji: "tsukue", arti: "meja" },
      { kata: "窓 (まど)", romaji: "mado", arti: "jendela" },
      { kata: "椅子 (いす)", romaji: "isu", arti: "bangku/kursi" },
      { kata: "ベッド", romaji: "beddo", arti: "ranjang" },
      { kata: "本棚 (ほんだな)", romaji: "hondana", arti: "rak buku" },
      { kata: "玄関 (げんかん)", romaji: "genkan", arti: "pintu gerbang depan" },
      { kata: "庭 (にわ)", romaji: "niwa", arti: "halaman" },
      { kata: "台所 (だいどころ)", romaji: "daidokoro", arti: "dapur" },
      { kata: "お風呂 (おふろ)", romaji: "ofuro", arti: "kamar mandi" },
      { kata: "お手洗い (おてあらい) / トイレ", romaji: "otearai / toire", arti: "toilet" },
      { kata: "ドア", romaji: "doa", arti: "pintu" },
      { kata: "入り口 (いりぐち)", romaji: "iriguchi", arti: "pintu masuk" },
      { kata: "出口 (でぐち)", romaji: "deguchi", arti: "pintu keluar" },
      { kata: "門 (もん)", romaji: "mon", arti: "gerbang" },
      { kata: "鍵 (かぎ)", romaji: "kagi", arti: "kunci" },
      { kata: "階段 (かいだん)", romaji: "kaidan", arti: "tangga" },
      { kata: "アパート", romaji: "apaato", arti: "apartement" },
      { kata: "建物 (たてもの)", romaji: "tatemono", arti: "bangunan" },
      { kata: "ホテル", romaji: "hoteru", arti: "hotel" },
      { kata: "エレベーター", romaji: "erebeetaa", arti: "elevator" },
      { kata: "冷蔵庫 (れいぞうこ)", romaji: "reizouko", arti: "kulkas" },
      { kata: "ストーブ", romaji: "sutoobu", arti: "penghangat ruangan" },
      { kata: "電気 (でんき)", romaji: "denki", arti: "listrik / lampu" },
      { kata: "電話 (でんわ)", romaji: "denwa", arti: "telepon" },
      { kata: "カレンダー", romaji: "karendaa", arti: "kalender" },
      { kata: "時計 (とけい)", romaji: "tokei", arti: "jam" },
      { kata: "花瓶 (かびん)", romaji: "kabin", arti: "pot bunga" },
      { kata: "灰皿 (はいざら)", romaji: "haizara", arti: "asbak" },
      { kata: "ラジオ", romaji: "rajio", arti: "radio" },
      { kata: "テレビ", romaji: "terebi", arti: "televisi" },
      { kata: "掃除 (そうじ)", romaji: "souji", arti: "bersih-bersih" },
      { kata: "洗濯 (せんたく)", romaji: "sentaku", arti: "mencuci pakaian" },
      { kata: "服 (ふく)", romaji: "fuku", arti: "pakaian / baju" },
      { kata: "靴 (くつ)", romaji: "kutsu", arti: "sepatu" },
      { kata: "鞄 (かばん)", romaji: "kaban", arti: "tas" },
      { kata: "傘 (かさ)", romaji: "kasa", arti: "payung" }
    ]
  },
  {
    key: "makanan-minuman",
    no: 3,
    nama: "Makanan & Minuman",
    icon: "&#127858;",
    contoh: "ご飯・水・肉・魚",
    kata: [
      { kata: "ご飯 (ごはん)", romaji: "gohan", arti: "nasi / makan" },
      { kata: "水 (みず)", romaji: "mizu", arti: "air" },
      { kata: "肉 (にく)", romaji: "niku", arti: "daging" },
      { kata: "魚 (さかな)", romaji: "sakana", arti: "ikan" },
      { kata: "豚肉 (ぶたにく)", romaji: "butaniku", arti: "daging babi" },
      { kata: "牛肉 (ぎゅうにく)", romaji: "gyuuniku", arti: "daging sapi" },
      { kata: "鶏肉 (とりにく)", romaji: "toriniku", arti: "daging ayam" },
      { kata: "牛乳 (ぎゅうにゅう)", romaji: "gyuunyuu", arti: "susu sapi" },
      { kata: "卵 (たまご)", romaji: "tamago", arti: "telur" },
      { kata: "野菜 (やさい)", romaji: "yasai", arti: "sayur" },
      { kata: "果物 (くだもの)", romaji: "kudamono", arti: "buah-buahan" },
      { kata: "食べ物 (たべもの)", romaji: "tabemono", arti: "makanan" },
      { kata: "飲み物 (のみもの)", romaji: "nomimono", arti: "minuman" },
      { kata: "パン", romaji: "pan", arti: "roti" },
      { kata: "バター", romaji: "battaa", arti: "mentega" },
      { kata: "お茶 (おちゃ)", romaji: "ocha", arti: "teh" },
      { kata: "お酒 (おさけ)", romaji: "osake", arti: "arak / alkohol" },
      { kata: "お菓子 (おかし)", romaji: "okashi", arti: "permen/snack" },
      { kata: "砂糖 (さとう)", romaji: "satou", arti: "gula" },
      { kata: "塩 (しお)", romaji: "shio", arti: "garam" },
      { kata: "醤油 (しょうゆ)", romaji: "shouyu", arti: "kecap asin" },
      { kata: "お弁当 (おべんとう)", romaji: "obentou", arti: "kotak makan siang" },
      { kata: "朝ご飯 (あさごはん)", romaji: "asagohan", arti: "sarapan pagi" },
      { kata: "昼ご飯 (ひるごはん)", romaji: "hirugohan", arti: "makan siang" },
      { kata: "晩ご飯 (ばんごはん)", romaji: "bangohan", arti: "makan malam" },
      { kata: "レストラン", romaji: "resutoran", arti: "restoran" },
      { kata: "食堂 (しょくどう)", romaji: "shokudou", arti: "kantin" },
      { kata: "喫茶店 (きっさてん)", romaji: "kissaten", arti: "kedai kopi" },
      { kata: "お皿 (おさら)", romaji: "osara", arti: "piring" },
      { kata: "コップ", romaji: "koppu", arti: "cangkir" },
      { kata: "グラス", romaji: "gurasu", arti: "gelas" },
      { kata: "スプーン", romaji: "supuun", arti: "sendok" },
      { kata: "フォーク", romaji: "fooku", arti: "garpu" },
      { kata: "ナイフ", romaji: "naifu", arti: "pisau" }
    ]
  },
  {
    key: "hewan-alam",
    no: 4,
    nama: "Hewan & Alam",
    icon: "&#127794;",
    contoh: "犬・猫・山・川",
    kata: [
      { kata: "動物 (どうぶつ)", romaji: "doubutsu", arti: "hewan/binatang" },
      { kata: "犬 (いぬ)", romaji: "inu", arti: "anjing" },
      { kata: "猫 (ねこ)", romaji: "neko", arti: "kucing" },
      { kata: "鳥 (とり)", romaji: "tori", arti: "burung" },
      { kata: "山 (やま)", romaji: "yama", arti: "gunung" },
      { kata: "川 (かわ)", romaji: "kawa", arti: "sungai" },
      { kata: "海 (うみ)", romaji: "umi", arti: "laut" },
      { kata: "池 (いけ)", romaji: "ike", arti: "kolam" },
      { kata: "空 (そら)", romaji: "sora", arti: "langit" },
      { kata: "星 (ほし)", romaji: "hoshi", arti: "bintang" },
      { kata: "花 (はな)", romaji: "hana", arti: "bunga" },
      { kata: "木 (き)", romaji: "ki", arti: "pohon" },
      { kata: "雲 (くも)", romaji: "kumo", arti: "awan" },
      { kata: "曇り (くもり)", romaji: "kumori", arti: "mendung" },
      { kata: "雨 (あめ)", romaji: "ame", arti: "hujan" },
      { kata: "雪 (ゆき)", romaji: "yuki", arti: "salju" },
      { kata: "風 (かぜ)", romaji: "kaze", arti: "angin" },
      { kata: "天気 (てんき)", romaji: "tenki", arti: "cuaca" },
      { kata: "春 (はる)", romaji: "haru", arti: "musim semi" },
      { kata: "夏 (なつ)", romaji: "natsu", arti: "musim panas" },
      { kata: "秋 (あき)", romaji: "aki", arti: "musim gugur" },
      { kata: "冬 (ふゆ)", romaji: "fuyu", arti: "musim dingin" },
      { kata: "冬休み (ふゆやすみ)", romaji: "fuyuyasumi", arti: "libur musim dingin" },
      { kata: "夏休み (なつやすみ)", romaji: "natsuyasumi", arti: "libur musim panas" },
      { kata: "国 (くに)", romaji: "kuni", arti: "negara" },
      { kata: "外国 (がいこく)", romaji: "gaikoku", arti: "negara luar" },
      { kata: "町 (まち)", romaji: "machi", arti: "kota" },
      { kata: "公園 (こうえん)", romaji: "kouen", arti: "taman" }
    ]
  },
  {
    key: "waktu-tanggal",
    no: 5,
    nama: "Waktu & Tanggal",
    icon: "&#128197;",
    contoh: "今日・明日・朝・夜",
    kata: [
      { kata: "今日 (きょう)", romaji: "kyou", arti: "hari ini" },
      { kata: "明日 (あした)", romaji: "ashita", arti: "besok" },
      { kata: "明後日 (あさって)", romaji: "asatte", arti: "besok lusa" },
      { kata: "昨日 (きのう)", romaji: "kinou", arti: "kemarin" },
      { kata: "一昨日 (おととい)", romaji: "ototoi", arti: "dua hari yang lalu" },
      { kata: "朝 (あさ)", romaji: "asa", arti: "pagi" },
      { kata: "今朝 (けさ)", romaji: "kesa", arti: "pagi ini" },
      { kata: "昼 (ひる)", romaji: "hiru", arti: "siang" },
      { kata: "夜 (よる) / 晩 (ばん)", romaji: "yoru / ban", arti: "malam" },
      { kata: "午前 (ごぜん)", romaji: "gozen", arti: "pagi/AM" },
      { kata: "午後 (ごご)", romaji: "gogo", arti: "sore/PM" },
      { kata: "今晩 (こんばん)", romaji: "konban", arti: "malam ini" },
      { kata: "今 (いま)", romaji: "ima", arti: "sekarang" },
      { kata: "まだ", romaji: "mada", arti: "masih" },
      { kata: "もう", romaji: "mou", arti: "sudah" },
      { kata: "時間 (じかん)", romaji: "jikan", arti: "waktu" },
      { kata: "いつ", romaji: "itsu", arti: "kapan" },
      { kata: "いつか", romaji: "itsuka", arti: "suatu saat" },
      { kata: "いつも", romaji: "itsumo", arti: "selalu" },
      { kata: "毎朝 (まいあさ)", romaji: "maiasa", arti: "setiap pagi" },
      { kata: "毎晩 (まいばん)", romaji: "maiban", arti: "setiap malam" },
      { kata: "毎日 (まいにち)", romaji: "mainichi", arti: "setiap hari" },
      { kata: "毎週 (まいしゅう)", romaji: "maishuu", arti: "setiap minggu" },
      { kata: "毎月 (まいつき)", romaji: "maitsuki", arti: "setiap bulan" },
      { kata: "毎年 (まいとし / まいねん)", romaji: "maitoshi / mainen", arti: "setiap tahun" },
      { kata: "先週 (せんしゅう)", romaji: "senshuu", arti: "minggu lalu" },
      { kata: "今週 (こんしゅう)", romaji: "konshuu", arti: "minggu ini" },
      { kata: "来週 (らいしゅう)", romaji: "raishuu", arti: "minggu depan" },
      { kata: "先月 (せんげつ)", romaji: "sengetsu", arti: "bulan lalu" },
      { kata: "今月 (こんげつ)", romaji: "kongetsu", arti: "bulan ini" },
      { kata: "来月 (らいげつ)", romaji: "raigetsu", arti: "bulan depan" },
      { kata: "去年 (きょねん)", romaji: "kyonen", arti: "tahun lalu" },
      { kata: "今年 (ことし)", romaji: "kotoshi", arti: "tahun ini" },
      { kata: "来年 (らいねん)", romaji: "rainen", arti: "tahun depan" },
      { kata: "一昨年 (おととし)", romaji: "ototoshi", arti: "dua tahun yang lalu" },
      { kata: "再来年 (さらいねん)", romaji: "sarainen", arti: "dua tahun kedepan" },
      { kata: "日曜日 (にちようび)", romaji: "nichiyoubi", arti: "hari minggu" },
      { kata: "月曜日 (げつようび)", romaji: "getsuyoubi", arti: "hari senin" },
      { kata: "火曜日 (かようび)", romaji: "kayoubi", arti: "hari selasa" },
      { kata: "水曜日 (すいようび)", romaji: "suiyoubi", arti: "hari rabu" },
      { kata: "木曜日 (もくようび)", romaji: "mokuyoubi", arti: "hari kamis" },
      { kata: "金曜日 (きんようび)", romaji: "kinyoubi", arti: "hari jumat" },
      { kata: "土曜日 (どようび)", romaji: "doyoubi", arti: "hari sabtu" },
      { kata: "一月 (いちがつ)", romaji: "ichigatsu", arti: "januari" },
      { kata: "二月 (にがつ)", romaji: "nigatsu", arti: "februari" },
      { kata: "三月 (さんがつ)", romaji: "sangatsu", arti: "maret" },
      { kata: "四月 (しがつ)", romaji: "shigatsu", arti: "april" },
      { kata: "五月 (ごがつ)", romaji: "gogatsu", arti: "mei" },
      { kata: "六月 (ろくがつ)", romaji: "rokugatsu", arti: "juni" },
      { kata: "七月 (しちがつ)", romaji: "shichigatsu", arti: "juli" },
      { kata: "八月 (はちがつ)", romaji: "hachigatsu", arti: "agustus" },
      { kata: "九月 (くがつ)", romaji: "kugatsu", arti: "september" },
      { kata: "十月 (じゅうがつ)", romaji: "juugatsu", arti: "oktober" },
      { kata: "十一月 (じゅういちがつ)", romaji: "juuichigatsu", arti: "november" },
      { kata: "十二月 (じゅうにがつ)", romaji: "juunigatsu", arti: "desember" },
      { kata: "一日 (ついたち)", romaji: "tsuitachi", arti: "tanggal 1" },
      { kata: "一日 (いちにち)", romaji: "ichinichi", arti: "satu hari" },
      { kata: "誕生日 (たんじょうび)", romaji: "tanjoubi", arti: "hari ulang tahun" },
      { kata: "初め (はじめ)", romaji: "hajime", arti: "permulaan" }
    ]
  },
  {
    key: "aktivitas-kata-kerja",
    no: 6,
    nama: "Aktivitas & Kata Kerja",
    icon: "&#127939;",
    contoh: "行く・食べる・見る",
    kata: [
      { kata: "行く (いく)", romaji: "iku", arti: "pergi" },
      { kata: "来る (くる)", romaji: "kuru", arti: "datang" },
      { kata: "帰る (かえる)", romaji: "kaeru", arti: "pulang" },
      { kata: "食べる (たべる)", romaji: "taberu", arti: "makan" },
      { kata: "飲む (のむ)", romaji: "nomu", arti: "minum" },
      { kata: "見る (みる)", romaji: "miru", arti: "melihat / menonton" },
      { kata: "聞く (きく)", romaji: "kiku", arti: "mendengar / bertanya" },
      { kata: "読む (よむ)", romaji: "yomu", arti: "membaca" },
      { kata: "書く (かく)", romaji: "kaku", arti: "menulis" },
      { kata: "話す (はなす)", romaji: "hanasu", arti: "berbicara" },
      { kata: "買う (かう)", romaji: "kau", arti: "membeli" },
      { kata: "起きる (おきる)", romaji: "okiru", arti: "bangun" },
      { kata: "寝る (ねる)", romaji: "neru", arti: "tidur" },
      { kata: "立つ (たつ)", romaji: "tatsu", arti: "berdiri" },
      { kata: "座る (すわる)", romaji: "suwaru", arti: "duduk" },
      { kata: "会う (あう)", romaji: "au", arti: "bertemu" },
      { kata: "遊ぶ (あそぶ)", romaji: "asobu", arti: "bermain" },
      { kata: "勉強 (べんきょう)", romaji: "benkyou", arti: "belajar" },
      { kata: "仕事 (しごと)", romaji: "shigoto", arti: "pekerjaan" },
      { kata: "宿題 (しゅくだい)", romaji: "shukudai", arti: "pekerjaan rumah (PR)" },
      { kata: "授業 (じゅぎょう)", romaji: "jugyou", arti: "pelajaran / kelas" },
      { kata: "教室 (きょうしつ)", romaji: "kyoushitsu", arti: "ruang kelas" },
      { kata: "クラス", romaji: "kurasu", arti: "kelas" },
      { kata: "テスト", romaji: "tesuto", arti: "tes / ujian" },
      { kata: "作文 (さくぶん)", romaji: "sakubun", arti: "karangan / esai" },
      { kata: "質問 (しつもん)", romaji: "shitsumon", arti: "pertanyaan" },
      { kata: "問題 (もんだい)", romaji: "mondai", arti: "masalah / soal" },
      { kata: "練習 (れんしゅう)", romaji: "renshuu", arti: "berlatih" },
      { kata: "買い物 (かいもの)", romaji: "kaimono", arti: "belanja" },
      { kata: "散歩 (さんぽ)", romaji: "sanpo", arti: "jalan-jalan" },
      { kata: "旅行 (りょこう)", romaji: "ryokou", arti: "tamasya / travel" },
      { kata: "料理 (りょうり)", romaji: "ryouri", arti: "masakan / memasak" },
      { kata: "結婚 (けっこん)", romaji: "kekkon", arti: "pernikahan" },
      { kata: "写真 (しゃしん)", romaji: "shashin", arti: "foto" },
      { kata: "絵 (え)", romaji: "e", arti: "gambar/lukisan" },
      { kata: "映画 (えいが)", romaji: "eiga", arti: "film" },
      { kata: "映画館 (えいがかん)", romaji: "eigakan", arti: "bioskop" },
      { kata: "音楽 (おんがく)", romaji: "ongaku", arti: "musik" },
      { kata: "歌 (うた)", romaji: "uta", arti: "lagu" },
      { kata: "スポーツ", romaji: "supootsu", arti: "olah raga" },
      { kata: "パーティ", romaji: "paati", arti: "pesta" },
      { kata: "ニュース", romaji: "nyuusu", arti: "berita" },
      { kata: "もしもし", romaji: "moshimoshi", arti: "halo (ditelpon)" }
    ]
  },
  {
    key: "sifat-kondisi",
    no: 7,
    nama: "Sifat & Kondisi",
    icon: "&#128522;",
    contoh: "大きい・小さい・新しい",
    kata: [
      { kata: "大きい (おおきい)", romaji: "ooki-i", arti: "besar" },
      { kata: "小さい (ちいさい)", romaji: "chiisa-i", arti: "kecil" },
      { kata: "新しい (あたらしい)", romaji: "atarashi-i", arti: "baru" },
      { kata: "古い (ふるい)", romaji: "furu-i", arti: "lama, tua" },
      { kata: "高い (たかい)", romaji: "taka-i", arti: "mahal, tinggi" },
      { kata: "安い (やすい)", romaji: "yasu-i", arti: "murah" },
      { kata: "長い (ながい)", romaji: "naga-i", arti: "panjang" },
      { kata: "短い (みじかい)", romaji: "mijika-i", arti: "pendek" },
      { kata: "多い (おおい)", romaji: "oo-i", arti: "banyak" },
      { kata: "少ない (すくない)", romaji: "sukuna-i", arti: "sedikit" },
      { kata: "早い (はやい)", romaji: "haya-i", arti: "cepat (waktu)" },
      { kata: "速い (はやい)", romaji: "haya-i", arti: "cepat (kelajuan)" },
      { kata: "遅い (おそい)", romaji: "oso-i", arti: "lambat" },
      { kata: "重い (おもい)", romaji: "omo-i", arti: "berat" },
      { kata: "軽い (かるい)", romaji: "karu-i", arti: "ringan" },
      { kata: "強い (つよい)", romaji: "tsuyo-i", arti: "kuat" },
      { kata: "弱い (よわい)", romaji: "yowa-i", arti: "lemah" },
      { kata: "暑い (あつい)", romaji: "atsu-i", arti: "panas (cuaca/suhu udara)" },
      { kata: "熱い (あつい)", romaji: "atsu-i", arti: "panas (benda/suhu)" },
      { kata: "蒸し暑い (むしあつい)", romaji: "mushiatsu-i", arti: "panas gerah" },
      { kata: "寒い (さむい)", romaji: "samu-i", arti: "dingin (cuaca)" },
      { kata: "冷たい (つめたい)", romaji: "tsumeta-i", arti: "dingin (benda)" },
      { kata: "涼しい (すずしい)", romaji: "suzushi-i", arti: "sejuk" },
      { kata: "暖かい (あたたかい)", romaji: "atataka-i", arti: "hangat" },
      { kata: "明るい (あかるい)", romaji: "akaru-i", arti: "terang, riang" },
      { kata: "暗い (くらい)", romaji: "kura-i", arti: "gelap, suram" },
      { kata: "難しい (むずかしい)", romaji: "muzukashi-i", arti: "sulit" },
      { kata: "易しい (やさしい)", romaji: "yasashi-i", arti: "mudah" },
      { kata: "優しい (やさしい)", romaji: "yasashi-i", arti: "baik hati, ramah" },
      { kata: "忙しい (いそがしい)", romaji: "isogashi-i", arti: "sibuk" },
      { kata: "楽しい (たのしい)", romaji: "tanoshi-i", arti: "menyenangkan" },
      { kata: "面白い (おもしろい)", romaji: "omoshiro-i", arti: "menarik, lucu" },
      { kata: "悲しい (かなしい)", romaji: "kanashi-i", arti: "sedih" },
      { kata: "寂しい (さびしい)", romaji: "sabishi-i", arti: "merasa sepi" },
      { kata: "痛い (いたい)", romaji: "ita-i", arti: "merasa nyeri, sakit" },
      { kata: "眠い (ねむい)", romaji: "nemu-i", arti: "mengantuk" },
      { kata: "怖い (こわい)", romaji: "kowa-i", arti: "takut" },
      { kata: "危ない (あぶない)", romaji: "abuna-i", arti: "berbahaya" },
      { kata: "汚い (きたない)", romaji: "kitana-i", arti: "kotor" },
      { kata: "うるさい", romaji: "urusa-i", arti: "berisik" },
      { kata: "可愛い (かわいい)", romaji: "kawai-i", arti: "cantik, lucu, imut" },
      { kata: "美しい (うつくしい)", romaji: "utsukushi-i", arti: "indah" },
      { kata: "いい / よい", romaji: "i-i / yo-i", arti: "bagus / baik" },
      { kata: "悪い (わるい)", romaji: "waru-i", arti: "jelek / buruk" },
      { kata: "正しい (ただしい)", romaji: "tadashi-i", arti: "benar" },
      { kata: "おかしい", romaji: "okashi-i", arti: "aneh, lucu" },
      { kata: "親しい (したしい)", romaji: "shitashi-i", arti: "akrab" },
      { kata: "詳しい (くわしい)", romaji: "kuwashi-i", arti: "detail" },
      { kata: "珍しい (めずらしい)", romaji: "mezurashi-i", arti: "langka" },
      { kata: "素晴らしい (すばらしい)", romaji: "subarashi-i", arti: "luar biasa" },
      { kata: "恥ずかしい (はずかしい)", romaji: "hazukashi-i", arti: "malu" },
      { kata: "羨ましい (うらやましい)", romaji: "urayamashi-i", arti: "iri hati" },
      { kata: "欲しい (ほしい)", romaji: "hoshi-i", arti: "ingin mendapatkan (benda)" },
      { kata: "懐かしい (なつかしい)", romaji: "natsukashi-i", arti: "terkenang" },
      { kata: "厳しい (きびしい)", romaji: "kibishi-i", arti: "tegas / ketat" },
      { kata: "丸い (まるい)", romaji: "maru-i", arti: "bundar, bulat" },
      { kata: "太い (ふとい)", romaji: "futo-i", arti: "gemuk, tebal (benda)" },
      { kata: "細い (ほそい)", romaji: "hoso-i", arti: "ramping, tipis" },
      { kata: "厚い (あつい)", romaji: "atsu-i", arti: "tebal (buku/benda)" },
      { kata: "固い (かたい)", romaji: "kata-i", arti: "keras" },
      { kata: "柔らかい (やわらかい)", romaji: "yawaraka-i", arti: "lunak / lembut" },
      { kata: "粗い (あらい)", romaji: "ara-i", arti: "kasar" },
      { kata: "細かい (こまかい)", romaji: "komaka-i", arti: "kecil / rinci" },
      { kata: "ひどい", romaji: "hido-i", arti: "kejam / parah" },
      { kata: "近い (ちかい)", romaji: "chika-i", arti: "dekat" },
      { kata: "遠い (とおい)", romaji: "too-i", arti: "jauh" },
      { kata: "低い (ひくい)", romaji: "hiku-i", arti: "rendah / pendek" },
      { kata: "無い (ない)", romaji: "na-i", arti: "tidak ada" },
      { kata: "不思議 (ふしぎ)", romaji: "fushigi", arti: "ajaib" },
      { kata: "活発 (かっぱつ)", romaji: "kappatsu", arti: "aktif" },
      { kata: "安全 (あんぜん)", romaji: "anzen", arti: "aman" },
      { kata: "変 (へん)", romaji: "hen", arti: "aneh" },
      { kata: "幸せ (しあわせ)", romaji: "shiawase", arti: "bahagia" },
      { kata: "親切 (しんせつ)", romaji: "shinsetsu", arti: "baik hati, ramah" },
      { kata: "自由 (じゆう)", romaji: "jiyuu", arti: "bebas" },
      { kata: "大嫌い (だいきらい)", romaji: "daikirai", arti: "benci sekali" },
      { kata: "危険 (きけん)", romaji: "kiken", arti: "berbahaya" },
      { kata: "色々 (いろいろ)", romaji: "iroiro", arti: "bermacam-macam" },
      { kata: "わがまま", romaji: "wagamama", arti: "bersifat egois" },
      { kata: "神経質 (しんけいしつ)", romaji: "shinkeeshitsu", arti: "sensitif" },
      { kata: "意地悪 (いじわる)", romaji: "ijiwaru", arti: "tega, jahat" },
      { kata: "不安 (ふあん)", romaji: "fuan", arti: "cemas" },
      { kata: "十分 (じゅうぶん)", romaji: "juubun", arti: "cukup" },
      { kata: "楽 (らく)", romaji: "raku", arti: "enteng, mudah, nyaman" },
      { kata: "ハンサム", romaji: "hansamu", arti: "ganteng" },
      { kata: "頑固 (がんこ)", romaji: "ganko", arti: "keras kepala" },
      { kata: "心配 (しんぱい)", romaji: "shinpai", arti: "khawatir" },
      { kata: "特別 (とくべつ)", romaji: "tokubetsu", arti: "khusus, spesial" },
      { kata: "丈夫 (じょうぶ)", romaji: "joubu", arti: "kuat / kokoh" },
      { kata: "別 (べつ)", romaji: "betsu", arti: "lain, beda" },
      { kata: "立派 (りっぱ)", romaji: "rippa", arti: "megah, layak dihormati" },
      { kata: "急 (きゅう)", romaji: "kyuu", arti: "mendadak" },
      { kata: "邪魔 (じゃま)", romaji: "jama", arti: "mengganggu" },
      { kata: "残念 (ざんねん)", romaji: "zannen", arti: "menyayangkan / kecewa" },
      { kata: "豪華 (ごうか)", romaji: "gouka", arti: "mewah" },
      { kata: "簡単 (かんたん)", romaji: "kantan", arti: "mudah / gampang" },
      { kata: "無理 (むり)", romaji: "muri", arti: "mustahil / tidak mungkin" },
      { kata: "上手 (じょうず)", romaji: "jouzu", arti: "pandai / mahir" },
      { kata: "得意 (とくい)", romaji: "tokui", arti: "pandai, jago (diri sendiri)" },
      { kata: "素直 (すなお)", romaji: "sunao", arti: "patuh, polos" },
      { kata: "大事 (だいじ)", romaji: "daiji", arti: "penting" },
      { kata: "大切 (たいせつ)", romaji: "taisetsu", arti: "penting / berharga" },
      { kata: "必要 (ひつよう)", romaji: "hitsuyou", arti: "perlu / butuh" },
      { kata: "盛ん (さかん)", romaji: "sakan", arti: "popular" },
      { kata: "便利 (べんり)", romaji: "benri", arti: "praktis / praktis" },
      { kata: "真面目 (まじめ)", romaji: "majime", arti: "rajin, serius, jujur" },
      { kata: "複雑 (ふくざつ)", romaji: "fukuzatsu", arti: "rumit" },
      { kata: "同じ (おなじ)", romaji: "onaji", arti: "sama" },
      { kata: "暇 (ひま)", romaji: "hima", arti: "senggang / luang" },
      { kata: "無駄 (むだ)", romaji: "muda", arti: "sia-sia" },
      { kata: "丁寧 (ていねい)", romaji: "teinei", arti: "sopan, halus, teliti" },
      { kata: "好き (すき)", romaji: "suki", arti: "suka" },
      { kata: "大好き (だいすき)", romaji: "daisuki", arti: "suka sekali" },
      { kata: "静か (しずか)", romaji: "shizuka", arti: "tenang / sepi" },
      { kata: "適当 (てきとう)", romaji: "tekitou", arti: "tepat, yang sesuai" },
      { kata: "有名 (ゆうめい)", romaji: "yuumei", arti: "terkenal" },
      { kata: "大丈夫 (だいじょうぶ)", romaji: "daijoubu", arti: "tidak apa apa / okey" },
      { kata: "勝ち気 (かちき)", romaji: "kachiki", arti: "tidak mau kalah" },
      { kata: "下手 (へた)", romaji: "heta", arti: "tidak pandai / buruk" },
      { kata: "不便 (ふべん)", romaji: "fuben", arti: "tidak praktis" },
      { kata: "不真面目 (ふまじめ)", romaji: "fumajime", arti: "tidak serius" },
      { kata: "嫌 (いや)", romaji: "iya", arti: "tidak suka / benci" },
      { kata: "伝統的 (でんとうてき)", romaji: "dentouteki", arti: "tradisional" },
      { kata: "誠実 (せいじつ)", romaji: "seijitsu", arti: "tulus hati, setia" },
      { kata: "きれい", romaji: "kirei", arti: "cantik / bersih" }
    ]
  },
  {
    key: "tempat-arah",
    no: 8,
    nama: "Tempat & Arah",
    icon: "&#128205;",
    contoh: "上・下・前・後",
    kata: [
      { kata: "上 (うえ)", romaji: "ue", arti: "atas" },
      { kata: "下 (した)", romaji: "shita", arti: "bawah" },
      { kata: "前 (まえ)", romaji: "mae", arti: "depan/sebelum" },
      { kata: "後ろ (うしろ)", romaji: "ushiro", arti: "belakang" },
      { kata: "左 (ひだり)", romaji: "hidari", arti: "kiri" },
      { kata: "右 (みぎ)", romaji: "migi", arti: "kanan" },
      { kata: "中 (なか)", romaji: "naka", arti: "dalam" },
      { kata: "外 (そと)", romaji: "soto", arti: "luar" },
      { kata: "隣 (となり)", romaji: "tonari", arti: "sebelah / tetangga" },
      { kata: "東 (ひがし)", romaji: "higashi", arti: "timur" },
      { kata: "西 (にし)", romaji: "nishi", arti: "barat" },
      { kata: "南 (みなみ)", romaji: "minami", arti: "selatan" },
      { kata: "北 (きた)", romaji: "kita", arti: "utara" },
      { kata: "側 (そば)", romaji: "soba", arti: "di sisi / dekat" },
      { kata: "所 (ところ)", romaji: "tokoro", arti: "tempat" },
      { kata: "角 (かど)", romaji: "kado", arti: "sudut / belokan" },
      { kata: "道 (みち)", romaji: "michi", arti: "jalan" },
      { kata: "駅 (えき)", romaji: "eki", arti: "stasiun" },
      { kata: "銀行 (ぎんこう)", romaji: "ginkou", arti: "bank" },
      { kata: "交番 (こうばん)", romaji: "kouban", arti: "pos polisi" },
      { kata: "大使館 (たいしかん)", romaji: "taishikan", arti: "kedutaan" },
      { kata: "学校 (がっこう)", romaji: "gakkou", arti: "sekolahan" },
      { kata: "大学 (だいがく)", romaji: "daigaku", arti: "universitas" },
      { kata: "図書館 (としょかん)", romaji: "toshokan", arti: "perpustakaan" },
      { kata: "デパート", romaji: "depaato", arti: "departement store" },
      { kata: "八百屋 (やおや)", romaji: "yaoya", arti: "toko sayuran" },
      { kata: "病院 (びょういん)", romaji: "byouin", arti: "rumah sakit" }
    ]
  },
  {
    key: "angka-jumlah",
    no: 9,
    nama: "Angka & Jumlah",
    icon: "&#128290;",
    contoh: "一・二・三・何",
    kata: [
      { kata: "一 (いち)", romaji: "ichi", arti: "satu" },
      { kata: "一つ (ひとつ)", romaji: "hitotsu", arti: "sebuah" },
      { kata: "二つ (ふたつ)", romaji: "futatsu", arti: "dua buah" },
      { kata: "三つ (みっつ)", romaji: "mittsu", arti: "tiga buah" },
      { kata: "十 (じゅう)", romaji: "juu", arti: "sepuluh" },
      { kata: "百 (ひゃく)", romaji: "hyaku", arti: "seratus" },
      { kata: "千 (せん / ち)", romaji: "sen / chi", arti: "seribu" },
      { kata: "万 (まん)", romaji: "man", arti: "sepuluh ribu" },
      { kata: "六 (ろく)", romaji: "roku", arti: "enam" },
      { kata: "九 (きゅう / く)", romaji: "kyuu / ku", arti: "sembilan" },
      { kata: "四 (し / よん)", romaji: "shi / yon", arti: "empat" },
      { kata: "何 (なに / なん)", romaji: "nani / nan", arti: "apa / berapa" },
      { kata: "一番 (いちばん)", romaji: "ichiban", arti: "paling / nomor satu" },
      { kata: "全部 (ぜんぶ)", romaji: "zenbu", arti: "semuanya" },
      { kata: "ゼロ", romaji: "zero", arti: "nol" },
      { kata: "キロ", romaji: "kiro", arti: "kilo" },
      { kata: "グラム", romaji: "guramu", arti: "gram" },
      { kata: "メートル", romaji: "meetoru", arti: "meter" },
      { kata: "半分 (はんぶん)", romaji: "hanbun", arti: "setengah" }
    ]
  },
  {
    key: "percakapan",
    no: 10,
    nama: "Percakapan Sehari-hari",
    icon: "&#128172;",
    contoh: "ありがとう・はい・いいえ",
    kata: [
      { kata: "勿論 (もちろん)", romaji: "mochiron", arti: "tentu" },
      { kata: "しかし", romaji: "shikashi", arti: "tetapi" },
      { kata: "また", romaji: "mata", arti: "lagi / sampai jumpa" },
      { kata: "もっと", romaji: "motto", arti: "lebih" },
      { kata: "あまり", romaji: "amari", arti: "tidak begitu (diikuti kalimat negatif)" },
      { kata: "こんな", romaji: "konna", arti: "seperti ini" },
      { kata: "そんな", romaji: "sonna", arti: "seperti itu" },
      { kata: "他 (ほか)", romaji: "hoka", arti: "yang lain" },
      { kata: "一緒 (いっしょ)", romaji: "issho", arti: "bersama" },
      { kata: "自分 (じぶん)", romaji: "jibun", arti: "diri sendiri" },
      { kata: "意味 (いみ)", romaji: "imi", arti: "arti / makna" },
      { kata: "言葉 (ことば)", romaji: "kotoba", arti: "kata-kata / bahasa" },
      { kata: "ありがとう", romaji: "arigatou", arti: "terima kasih" },
      { kata: "はい", romaji: "hai", arti: "ya" },
      { kata: "いいえ", romaji: "iie", arti: "tidak" },
      { kata: "すみません", romaji: "sumimasen", arti: "maaf / permisi" }
    ]
  },
  {
    key: "warna",
    no: 11,
    nama: "Warna",
    icon: "&#127912;",
    contoh: "赤・青・白・黒",
    kata: [
      { kata: "赤 (あか)", romaji: "aka", arti: "merah" },
      { kata: "青 (あお)", romaji: "ao", arti: "biru" },
      { kata: "白 (しろ)", romaji: "shiro", arti: "putih" },
      { kata: "黒 (くろ)", romaji: "kuro", arti: "hitam" },
      { kata: "黄色 (きいろ)", romaji: "kiiro", arti: "kuning" },
      { kata: "緑 (みどり)", romaji: "midori", arti: "hijau" },
      { kata: "ピンク", romaji: "pinku", arti: "merah muda" },
      { kata: "茶色 (ちゃいろ)", romaji: "chairo", arti: "cokelat" },
      { kata: "色 (いろ)", romaji: "iro", arti: "warna" }
    ]
  },
  {
    key: "pekerjaan",
    no: 12,
    nama: "Pekerjaan",
    icon: "&#128188;",
    contoh: "先生・医者・会社員",
    kata: [
      { kata: "先生 (せんせい)", romaji: "sensei", arti: "guru / pengajar" },
      { kata: "医者 (いしゃ)", romaji: "isha", arti: "dokter" },
      { kata: "会社 (かいしゃ)", romaji: "kaisha", arti: "perusahaan" },
      { kata: "会社員 (かいしゃいん)", romaji: "kaishain", arti: "pegawai perusahaan" },
      { kata: "学生 (がくせい)", romaji: "gakusei", arti: "pelajar / mahasiswa" },
      { kata: "生徒 (せいと)", romaji: "seito", arti: "murid" },
      { kata: "警官 (けいかん)", romaji: "keikan", arti: "polisi" }
    ]
  }
];

// Kunci -> objek kategori, untuk lookup cepat di render.
var KOSAKATA_CATEGORY_MAP = {};
for (var _i = 0; _i < KOSAKATA_CATEGORIES.length; _i++) {
  KOSAKATA_CATEGORY_MAP[KOSAKATA_CATEGORIES[_i].key] = KOSAKATA_CATEGORIES[_i];
}
